import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sharedModules = [
  'rules-2026.js',
  'insurance-layout.js',
  'questions.js',
  'flow.js',
  'state.js',
  'deductions-step4.js',
  'calculations.js',
  'form-guide.js',
  'insurance-supplement-v2.js',
];
const targets = [{ modules: [...sharedModules, 'wizard-v2.js', 'form-preview-v2.js', 'app-v2.js'], output: 'docs/app.bundle.js' }];

function parseImports(source, file) {
  const imports = [];
  const cleaned = source.replace(/^import\s+\{([^}]+)\}\s+from\s+['"]\.\/([^'"]+)['"];?\s*$/gm, (_line, names, dependency) => {
    for (const item of names.split(',')) {
      const [imported, local] = item.trim().split(/\s+as\s+/);
      if (!imported) continue;
      imports.push(`${imported}${local ? `: ${local}` : ''}`);
    }
    return '';
  });
  if (/^import\s/m.test(cleaned)) throw new Error(`Unsupported import syntax in ${file}`);
  return { imports, source: cleaned };
}

for (const target of targets) {
  const output = [
    '/* Generated by scripts/build-site.mjs. Edit source modules, not this file. */',
    'window.YearEndApp = window.YearEndApp || {};',
  ];
  for (const file of target.modules) {
    const original = await readFile(resolve(root, 'src', file), 'utf8');
    const { imports, source: withoutImports } = parseImports(original, file);
    const exports = [];
    const source = withoutImports.replace(/^export\s+(?=(?:function|const|let|class)\s)/gm, '');
    for (const match of withoutImports.matchAll(/^export\s+(?:function|const|let|class)\s+([A-Za-z_$][\w$]*)/gm)) exports.push(match[1]);
    if (/\bexport\s/.test(source)) throw new Error(`Unsupported export syntax in ${file}`);
    output.push(`\n/* ${file} */`, '(function (app) {');
    if (imports.length) output.push(`  const { ${imports.join(', ')} } = app;`);
    output.push(source, `  Object.assign(app, { ${exports.join(', ')} });`, '}(window.YearEndApp));');
  }
  await writeFile(resolve(root, target.output), `${output.join('\n')}\n`, 'utf8');
  console.log(`Generated ${target.output} from ${target.modules.length} source modules.`);
}
