// Questions, paper-entry labels and unknown-answer guidance. Calculations are separate.
import { TAX_RULES_2026 } from './rules-2026.js';
import { INSURANCE_INPUT_LIMIT } from './insurance-layout.js';
const salaryLimitMan=TAX_RULES_2026.thresholds.salaryLimitForYearEndAdjustment/10000;
export const QUESTIONS = {
  target: { text: '今年、この会社で年末調整を受ける予定ですか？', choices: ['はい','いいえ','分からない'], unknown: '年末調整を受ける予定か、会社の担当者へ確認してください。' },
  form: { text: 'この会社へ「扶養控除等申告書」を提出していますか？', hint: '扶養家族がいない方も提出する書類です。', choices: ['はい','いいえ','分からない'], unknown: '扶養控除等申告書を提出済みか、会社の担当者へ確認してください。' },
  salaryLimit: { text: `今年1年間の給与収入は${salaryLimitMan.toLocaleString('ja-JP')}万円を超える見込みですか？`, hint: '手取りではなく、税金や社会保険料を引く前の金額です。', choices: [`${salaryLimitMan.toLocaleString('ja-JP')}万円以下`,`${salaryLimitMan.toLocaleString('ja-JP')}万円超`,'分からない'], unknown: '給与収入が基準を超えるか、会社の担当者へ確認してください。' },
  changedJob: { text: '今年、別の会社から転職してきましたか？', choices: ['はい','いいえ'] },
  priorSlip: { text: '前の勤務先から源泉徴収票を受け取っていますか？', choices: ['はい','まだ','分からない'], unknown: '前職の源泉徴収票を受け取れる時期と提出方法を確認してください。' },
  otherSalary: { text: '今年、この会社以外から給与を受け取りましたか？', choices: ['はい','いいえ'] },
  allSalary: { text: 'すべての勤務先を合わせた給与収入はいくらになりそうですか？', hint: '手取りではなく、税金や社会保険料を引く前の金額です。', input: 'money', unknown:'源泉徴収票や給与明細から給与収入を確認してください。' },
  ownSalary: { text: '今年、この会社から受け取る給与収入はいくらになりそうですか？', hint: '手取りではなく、税金や社会保険料を引く前の金額です。', input: 'money', unknown:'給与明細等で給与収入を確認してください。' },
  otherIncome: { text: '給与以外の収入がありますか？', choices: ['ない','公的年金','副業・事業所得','不動産所得','その他','分からない'], unknown: '給与以外の収入について、会社の担当者へ確認してください。' },
  spouse: { text: '配偶者はいますか？', choices: ['はい','いいえ'] },
  spouseShared: { text: '配偶者とは生活費を共にしていますか？', choices: ['はい','いいえ','分からない'], unknown: '配偶者との生活費の状況を会社の担当者へ確認してください。' },
  spouseClaimed: { text: '配偶者は、他の人の扶養親族等として申告されていますか？', choices: ['はい','いいえ','分からない'], unknown: '配偶者の申告状況を関係する方と確認してください。' },
  spouseAge: { text: '配偶者は2026年12月31日時点で何歳ですか？', hint: '配偶者控除額の区分確認に使います。', input: 'age' },
  spouseIncomeType: { text: '配偶者の今年の主な収入は何ですか？', choices: ['給与だけ','給与以外もある','収入なし','分からない'], unknown: '配偶者の収入内容を確認してください。' },
  spouseSalary: { text: '配偶者の今年1年間の給与収入はいくらになりそうですか？', hint: '手取りではなく総支給額です。', input: 'money', unknown:'配偶者の給与収入を確認してください。' },
  dependents: { text: '配偶者以外に、生活費を支えている家族はいますか？', choices: ['はい','いいえ'] },
  dependentCount: { text: '扶養している家族は何人いますか？', hint: '1〜10人の範囲で入力してください。', input: 'count' },
  dependentKin: { text: 'その方はあなたの親族ですか？', choices: ['はい','いいえ','分からない'], unknown: '家族が親族に当たるか会社の担当者へ確認してください。' },
  dependentAge: { text: '2026年12月31日時点の年齢を入力してください。', hint: '0〜120歳で入力してください。', input: 'age' },
  dependentIncome: { text: 'その方に今年収入がありますか？', choices: ['ない','給与がある','給与以外の所得がある','分からない'], unknown: 'その家族の収入について会社の担当者へ確認してください。' },
  dependentSalary: { text: 'その方の今年1年間の給与収入はいくらになりそうですか？', input: 'money', unknown:'扶養家族の給与収入を確認してください。' },
  dependentShared: { text: 'その方を、あなた以外の人も扶養として申告する予定ですか？', choices: ['はい','いいえ','分からない'], unknown: '扶養申告の重複がないか会社の担当者へ確認してください。' },
  dependentParent: { text: 'その方は、あなたまたは配偶者の父母・祖父母等ですか？', choices: ['はい','いいえ'] },
  dependentCohabit: { text: '普段一緒に暮らしていますか？', choices: ['はい','いいえ','老人ホーム等'] },
  lifeCount: { text: '入力する生命保険の契約・区分はいくつありますか？', hint: `同じ契約に一般・介護医療など複数の区分があれば、区分ごとに1件として入力します。1〜${INSURANCE_INPUT_LIMIT}件で入力してください。紙の欄を超えた分は、結果画面で添付別紙明細を作ります。`, input: 'count', max:INSURANCE_INPUT_LIMIT, unit:'件数' },
  lifeType: { text: '証明書に書かれている区分を選んでください。', choices: ['新生命保険料','旧生命保険料','介護医療保険料','新個人年金保険料','旧個人年金保険料','分からない'], unknown: '生命保険料の区分を会社の担当者へ確認してください。' },
  lifeAmount: { text: '証明書の申告額を入力してください。', input: 'money', unknown:'生命保険料控除証明書の申告額を確認してください。' },
  lifePaid: { text: 'この保険料を実際に支払ったのはあなたですか？', choices: ['はい','いいえ','分からない'], unknown: '保険料の支払者を会社の担当者へ確認してください。' },
  lifeRecipient: { text: '保険金・年金の受取人は誰ですか？', choices: ['本人','配偶者','親族','その他','分からない'], unknown: '保険金・年金の受取人を会社の担当者へ確認してください。' },
  lifeCompanyName: { text: '保険会社等の名称を入力してください。', hint: '控除証明書に記載された名称を入力します。', input: 'text', unknown: '生命保険の保険会社等の名称を控除証明書で確認してください。' },
  lifeInsuranceKind: { text: '保険等の種類を入力してください。', hint: '例：終身保険、医療保険、個人年金。証明書の表記を使います。', input: 'text', unknown: '生命保険の保険等の種類を控除証明書で確認してください。' },
  lifeInsurancePeriod: { text: '保険期間又は年金支払期間を入力してください。', hint: '例：終身、10年。個人年金は年金支払期間を証明書どおり入力します。', input: 'text', unknown: '生命保険の保険期間又は年金支払期間を確認してください。' },
  lifeHolderName: { text: '保険等の契約者の氏名を入力してください。', input: 'text', unknown: '生命保険の契約者の氏名を確認してください。' },
  lifeRecipientName: { text: '保険金等の受取人の氏名を入力してください。', hint: '契約者と同じ方なら、下のボタンで名前を再利用できます。', input: 'text', reuseHolder: true, unknown: '生命保険の受取人の氏名を確認してください。' },
  lifeRecipientRelationship: { text: '受取人とあなたの続柄を入力してください。', hint: '例：子、父、母。すでに本人・配偶者と回答した場合は質問しません。', input: 'text', unknown: '生命保険の受取人とあなたの続柄を確認してください。' },
  lifePensionStartDate: { text: '個人年金の支払開始日を入力してください。', hint: '控除証明書の表記を使います。例：令和18年4月1日。', input: 'text', unknown: '個人年金の支払開始日を控除証明書で確認してください。' },
  earthquakeCount: { text: '地震保険料控除証明書に記載された契約はいくつありますか？', hint: `1〜${INSURANCE_INPUT_LIMIT}件で入力してください。紙の欄を超えた分は、結果画面で添付別紙明細を作ります。`, input: 'count', max:INSURANCE_INPUT_LIMIT, unit:'件数' },
  earthquakeType: { text: '証明書の区分を選んでください。', choices: ['地震保険料','旧長期損害保険料','両方','分からない'], unknown: '地震保険料の区分を会社の担当者へ確認してください。' },
  earthquakeAmount: { text: '選んだ区分の証明書記載金額を入力してください。', input: 'money', unknown:'地震保険料控除証明書の金額を確認してください。' },
  earthquakeElection: { text: '同じ契約に地震保険料と旧長期損害保険料の両方がある場合、どちらで申告しますか？', choices: ['地震保険料','旧長期損害保険料','分からない'], unknown: '同一契約の控除区分の選択を担当者へ確認してください。' },
  earthquakePaid: { text: 'この保険料を実際に支払ったのはあなたですか？', choices: ['はい','いいえ','分からない'], unknown: '地震保険料の支払者を確認してください。' },
  earthquakeCompanyName: { text: '保険会社等の名称を入力してください。', input: 'text', unknown: '地震保険の保険会社等の名称を控除証明書で確認してください。' },
  earthquakeInsuranceKind: { text: '保険等の種類（目的）を入力してください。', hint: '例：住宅、家財。控除証明書の表記を使います。', input: 'text', unknown: '地震保険の保険等の種類（目的）を確認してください。' },
  earthquakeInsurancePeriod: { text: '保険期間を入力してください。', hint: '例：1年、5年。控除証明書の表記を使います。', input: 'text', unknown: '地震保険の保険期間を確認してください。' },
  earthquakeHolderName: { text: '保険等の契約者の氏名を入力してください。', input: 'text', unknown: '地震保険の契約者の氏名を確認してください。' },
  earthquakeInsuredName: { text: '保険の対象となった家屋等に居住又は家財を利用している方の氏名を入力してください。', hint: '契約者と同じ方なら、下のボタンで名前を再利用できます。', input: 'text', reuseHolder: true, unknown: '地震保険の家屋等に居住又は家財を利用している方の氏名を確認してください。' },
  earthquakeInsuredRelationship: { text: 'その方とあなたの続柄を入力してください。', hint: '例：本人、配偶者、子、父、母。', input: 'text', unknown: '地震保険の居住者等とあなたの続柄を確認してください。' },
  socialTypes: { text: '自分で支払った社会保険料の種類を選んでください。複数選べます。', multi: true, choices: ['国民年金','国民年金基金','家族分の社会保険料','その他'] },
  socialAmount: { text: '支払った金額を入力してください。', input: 'money', unknown:'給与天引き外に実際に支払った社会保険料を確認してください。' },
  idecoAmount: { text: '証明書に記載された掛金の金額を入力してください。', input: 'money', unknown:'対象掛金の控除証明書等に記載された金額を確認してください。' },
  idecoType: { text: '支払った掛金の種類を選んでください。', choices: ['小規模企業共済掛金','企業型年金加入者掛金','個人型年金加入者掛金（iDeCo）','心身障害者扶養共済掛金','複数種','分からない'], unknown: '掛金の対象範囲を証明書と担当者へ確認してください。' },
  disabilitySelf: { text: '本人に、障害者手帳・自治体の認定など障害者控除の対象となる状態がありますか？', choices: ['ない','一般障害者','特別障害者','分からない'], unknown: '障害者控除の区分と対象要件を担当者へ確認してください。' },
  disabilityFamily: { text: '配偶者または登録した扶養家族に、障害者控除の対象となる方がいますか？', choices: ['はい','いいえ','分からない'], unknown: '家族の障害者控除対象者を担当者へ確認してください。' },
  disabilityPerson: { text: 'この方の障害者控除の区分を選んでください。', choices: ['ない','一般障害者','特別障害者','分からない'], unknown: '障害者控除の区分を担当者へ確認してください。' },
  disabilityCohabit: { text: 'この特別障害者の方は、あなた・あなたの配偶者・あなたと生計を一にする親族のいずれかと同居していますか？', choices: ['はい','いいえ','分からない'], unknown: '同居特別障害者に当たるか担当者へ確認してください。' },
  parentStatus: { text: '2026年12月31日時点のあなたの婚姻状況はどれですか？', choices: ['婚姻中','未婚','離婚','死別・生死不明','分からない'], unknown: '年末時点の婚姻状況を担当者へ確認してください。' },
  deFactoPartner: { text: '現在、事実上婚姻関係と同様の事情にある方がいますか？', choices: ['はい','いいえ','分からない'], unknown: '事実婚関係の有無を担当者へ確認してください。' },
  parentChild: { text: 'あなたと生計を一にする子がいますか？', choices: ['はい','いいえ','分からない'], unknown: '子の生計状況を担当者へ確認してください。' },
  parentChildIncomeKnown: { text: 'その子の令和8年分の所得金額を確認できますか？', choices: ['はい','いいえ','分からない'], unknown: '子の所得金額を確認してください。' },
  parentChildIncome: { text: 'その子の令和8年分の合計所得金額はいくらですか？', hint: '給与収入そのものではなく、税法上の合計所得金額を入力します。金額を確認できない場合は「金額が分からない」を選んでください。', input: 'money', unknown:'子の合計所得金額を確認してください。' },
  parentChildClaimed: { text: 'その子は、あなた以外の人の扶養親族または同一生計配偶者として申告されますか？', choices: ['はい','いいえ','分からない'], unknown: '子の他の方による申告状況を担当者へ確認してください。' },
  widowGender: { text: 'あなたの性別を教えてください。', hint: '寡婦控除は女性が対象です。ひとり親控除は性別を問いません。', choices: ['女性','女性以外','分からない'], unknown: '寡婦控除の要件を担当者へ確認してください。' },
  student: { text: '2026年12月31日時点で学校に在学していますか？', choices: ['はい','いいえ','分からない'], unknown: '在学状況を担当者へ確認してください。' },
  studentSchool: { text: '在学先の種類を教えてください。', choices: ['小・中・高校、大学、高等専門学校','対象課程と確認済みの専修学校等','専修学校・各種学校・職業訓練校（課程未確認）','それ以外','分からない'], unknown: '学校・課程が勤労学生控除の対象か学校窓口へ確認してください。' },
  life: { text: '生命保険料控除証明書がありますか？', choices: ['はい','いいえ','分からない'], unknown: '生命保険料控除証明書の有無を確認してください。' },
  earthquake: { text: '地震保険料控除証明書がありますか？', choices: ['はい','いいえ','分からない'], unknown: '地震保険料控除証明書の有無を確認してください。' },
  social: { text: '給与から引かれているもの以外に、自分で社会保険料を支払いましたか？', hint: '例：国民年金、国民年金基金、家族分の社会保険料。', choices: ['はい','いいえ','分からない'], unknown: '給与天引き以外の社会保険料があるか確認してください。' },
  ideco: { text: '給与天引き以外に、対象となる小規模企業共済等の掛金を本人が支払いましたか？', hint: 'iDeCo、企業型年金の加入者掛金、小規模企業共済、心身障害者扶養共済など。給与から差し引かれた掛金は会社で控除するため、ここへ重ねて入力しません。', choices: ['はい','いいえ','分からない'], unknown: '給与天引き以外の掛金の種類・本人負担額と証明書を確認してください。' },
  housing: { text: '住宅ローン控除を受けていますか？', choices: ['はい','いいえ','分からない'], unknown: '住宅ローン控除の手続きについて確認してください。' },
  housingFirst: { text: '今年が住宅ローン控除の初年度ですか？', choices: ['はい','いいえ','分からない'], unknown: '住宅ローン控除の適用開始年を確認してください。' },
  housingDocs: { text: '住宅ローン控除の申告書・控除証明書がありますか？', choices: ['はい','いいえ','電子データ','分からない'], unknown: '申告書や控除証明書の取得方法を確認してください。' },
  housingBalance: { text: '金融機関の年末残高情報または残高証明書がありますか？', choices: ['はい','いいえ','電子連携','分からない'], unknown: '年末残高情報の受け取り方法を確認してください。' },
  special: { text: '次のうち、当てはまるものはありますか？', hint: '複数選べます。選び終わったら「選択を確定」を押してください。', choices: ['国外居住親族がいる','配偶者や扶養家族に事業所得がある','扶養を他の人も申告する可能性','年途中に結婚・離婚・出生・死亡','災害などの特殊事情','その他判断できないことがある','どれもない'], multi: true }
};
// 令和8年分 国税庁 保険料控除申告書（2026bun_04.pdf）の欄名。
export const INSURANCE_ENTRY_LABELS={
  lifeCompanyName:'保険会社等の名称',lifeInsuranceKind:'保険等の種類',lifeInsurancePeriod:'保険期間又は年金支払期間',lifeHolderName:'保険等の契約者の氏名',lifeRecipientName:'保険金等の受取人の氏名',lifeRecipientRelationship:'あなたとの続柄',lifePensionStartDate:'支払開始日',
  earthquakeCompanyName:'保険会社等の名称',earthquakeInsuranceKind:'保険等の種類（目的）',earthquakeInsurancePeriod:'保険期間',earthquakeHolderName:'保険等の契約者の氏名',earthquakeInsuredName:'保険等の対象となった家屋等に居住又は家財を利用している者の氏名',earthquakeInsuredRelationship:'あなたとの続柄'
};
for(const [id,label] of Object.entries(INSURANCE_ENTRY_LABELS))QUESTIONS[id].entryLabel=label;
